/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;                //paquetes importados
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Altauser extends javax.swing.JFrame {

    /**
     * Creates new form Altauser
     */
    
    public Altauser() {
        initComponents(); //los cambios que se hacen aqui se guardan en esta funcion autogenerada
        Toolkit mipantalla2 = Toolkit.getDefaultToolkit(); //obtiene informacion de la pantalla y lo guarda en el objeto
        setSize(1017,575);   // establece el tamaño de la pantalla 
        setLocationRelativeTo(null); // establece la posicion de la pantalla en el centro
        setTitle("InfoQuizz"); //Establece el titulo
        Image Icono = mipantalla2.getImage("src/proyectofinal/imagenes/preview.jpeg"); //Se crea un objeto de tipo Image
        setIconImage(Icono); // Se usa el objeto image para colocar icono
        
        //Objeto jPanel con color VistaColor
        jpColor jpVista2 = new jpColor(); //esta funcion hace el color degradado en el panel
        jpVista2.setSize(this.getSize());
        jpVista2.setVistaColor(153,206,195,0,0,0);
        jPanel1.add(jpVista2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        lblpass1 = new javax.swing.JLabel();
        btncreauser = new javax.swing.JButton();
        newUsername = new javax.swing.JTextField();
        newpass = new javax.swing.JPasswordField();
        btncancelar = new javax.swing.JButton();
        btnHecho = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 206, 195));

        jPanel2.setBackground(new java.awt.Color(153, 206, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblusername.setBackground(new java.awt.Color(255, 255, 255));
        lblusername.setFont(new java.awt.Font("Yu Gothic", 3, 18)); // NOI18N
        lblusername.setText("Nombre de Usuario:");
        lblusername.setAutoscrolls(true);
        lblusername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblpass1.setFont(new java.awt.Font("Yu Gothic", 3, 18)); // NOI18N
        lblpass1.setText("Contraseña:");
        lblpass1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btncreauser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncreauser.setText("Crear Usuario");
        btncreauser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncreauserMouseClicked(evt);
            }
        });

        newUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newUsernameFocusGained(evt);
            }
        });

        newpass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newpassFocusGained(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });

        btnHecho.setText("Hecho");
        btnHecho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHechoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHecho)
                .addGap(18, 18, 18)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncreauser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblpass1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblusername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newUsername)
                    .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusername)
                    .addComponent(newUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpass1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newpass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncreauser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHecho))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        // TODO add your handling code here:  //este es el codigo accion del boton cancelar
        Menu m3 = new Menu(); // se crea un objeto de tipo Menu
        m3.setVisible(true); // hace visible el frame
        m3.setResizable(false); // impide que se modifique el tamaño del frame
        dispose(); // cierra el frame actual
    }//GEN-LAST:event_btncancelarMouseClicked

    private void btncreauserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncreauserMouseClicked
        // TODO add your handling code here: // boton creacion de usuario
        String user = newUsername.getText().trim();  //guarda lo que tiene el campo user y quita espacios al inicio y final con trim()
        if(user.isEmpty()){ //Si esta vacio no pasa
            JOptionPane.showMessageDialog(null, "No ha ingresado el nombre de usuario");
            return; // el return sirve para reiniciar
        }
        char[] arraypass = newpass.getPassword(); //el campo contraseña regresa un array con los caracteres escritos
        String pass = new String(arraypass);//se declara una variable para convertir el array en cadena
        String clavereal = user.concat(pass); // para mayor seguridad la clave es el nombre de usuario y la conrseña juntos 
                                            //pero esto no lo hace el usuario, lo hace el programa
        if(pass.isEmpty()){ // si la clave esta vacia no entra al ciclo igual que la anterior
            JOptionPane.showMessageDialog(null, "No se ha ingresado la contraseña");
            return;
        }
        try{ // si los datos si estan llenos entra con el intento de la alta del usuario
            AccesoAleatorioU.creaArchUser(new File("Usuarios.dat")); // usa el metodo para crear el flujo 
            AccesoAleatorioU.añadeUsuario(new Usuario(user,clavereal)); // se usa el metodo crear usuario y se envia un objeto
                                                                        // de tipo usuario con el usuario y la clave real
            AccesoAleatorioU.cierraflujo(); // despues de la escritura se cierra el flujo
            JOptionPane.showMessageDialog(null, "¡Usuario registrado con éxito!"); //si esto es cierto regresa mensaje de exito
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error al registrar usuario");
        }
        newpass.setText("");
        newUsername.setText("");
    }//GEN-LAST:event_btncreauserMouseClicked
//los focus gained siven para seleccionar lo escrito en caso de querer dar de alta otro usuario, es solo estetico
    private void newUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newUsernameFocusGained
        // TODO add your handling code here:
        newUsername.selectAll();
    }//GEN-LAST:event_newUsernameFocusGained

    private void newpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newpassFocusGained
        // TODO add your handling code here:
        newpass.selectAll();
    }//GEN-LAST:event_newpassFocusGained

    private void btnHechoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHechoMouseClicked
        // TODO add your handling code here:
        Menu otrom = new Menu();
        otrom.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHechoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Altauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Altauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Altauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Altauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Altauser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHecho;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncreauser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblpass1;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField newUsername;
    private javax.swing.JPasswordField newpass;
    // End of variables declaration//GEN-END:variables
}
