/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.*;

/**
 *
 * @author andre
 */
public class ConsultAll extends javax.swing.JFrame {

    /**
     * Creates new form ConsultAll
     */
    public ConsultAll() {
        initComponents();
        Toolkit mipantalla5 = Toolkit.getDefaultToolkit();
        setSize(1017,575);
        setLocationRelativeTo(null);
        setTitle("InfoQuizz");
        Image Icono = mipantalla5.getImage("src/proyectofinal/imagenes/preview.jpeg");
        setIconImage(Icono);
        setResizable(false);
        back.setVisible(false);
        contenedorpreg.setEditable(false);
        
        //Objeto jPanel con color VistaColor
        jpColor jpVista6 = new jpColor();
        jpVista6.setSize(this.getSize());
        jpVista6.setVistaColor(153,206,195,0,0,0);
        panelconsultall.add(jpVista6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelconsultall = new javax.swing.JPanel();
        muestrapregs = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        contenedorpreg = new javax.swing.JTextArea();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        muestrapregs.setText("Mostrar");
        muestrapregs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                muestrapregsMouseClicked(evt);
            }
        });

        contenedorpreg.setColumns(20);
        contenedorpreg.setRows(5);
        jScrollPane2.setViewportView(contenedorpreg);

        back.setText("Regresar");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelconsultallLayout = new javax.swing.GroupLayout(panelconsultall);
        panelconsultall.setLayout(panelconsultallLayout);
        panelconsultallLayout.setHorizontalGroup(
            panelconsultallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelconsultallLayout.createSequentialGroup()
                .addGroup(panelconsultallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelconsultallLayout.createSequentialGroup()
                        .addGap(791, 791, 791)
                        .addComponent(back)
                        .addGap(18, 18, 18)
                        .addComponent(muestrapregs))
                    .addGroup(panelconsultallLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelconsultallLayout.setVerticalGroup(
            panelconsultallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelconsultallLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelconsultallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muestrapregs)
                    .addComponent(back))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelconsultall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelconsultall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void muestrapregsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muestrapregsMouseClicked
        try {
            // TODO add your handling code here:
            File archlect = new File("Preguntas.dat");
            RandomAccessFile entrada = new RandomAccessFile(archlect,"r");
            int Numpreg = (int)Math.ceil((double)entrada.length()/800);
            String tema,subt,preg,res1,res2,res3;
            for (int i=0; i <= Numpreg ; i++){
                entrada.seek(i*800);
                tema = entrada.readUTF();
                subt = entrada.readUTF();
                preg = entrada.readUTF();
                res1 = entrada.readUTF();
                entrada.readBoolean();
                res2 = entrada.readUTF();
                entrada.readBoolean();
                res3 = entrada.readUTF();
                entrada.readBoolean();
                
                contenedorpreg.append(tema+"\n");
                contenedorpreg.append(subt+"\n");
                contenedorpreg.append(preg+"\n");
                contenedorpreg.append(res1+"\n");
                contenedorpreg.append(res2+"\n");
                contenedorpreg.append(res3+"\n");
                contenedorpreg.append("\n");
                contenedorpreg.append("*****************************************");
                contenedorpreg.append("\n");
            }
        } catch (FileNotFoundException ex) {
        
        }catch(IOException e){
            
        }
        back.setVisible(true);
        muestrapregs.setEnabled(false);
    }//GEN-LAST:event_muestrapregsMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        PantPrincipalAdmin p = new PantPrincipalAdmin();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextArea contenedorpreg;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton muestrapregs;
    private javax.swing.JPanel panelconsultall;
    // End of variables declaration//GEN-END:variables
}
