/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;

/**
 *
 * @author andre
 */
public class ConsultaInfoUsers extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaInfoUsers
     */
    public ConsultaInfoUsers() {
        initComponents();
        Toolkit mipantalla5 = Toolkit.getDefaultToolkit();
        setSize(1017,575);
        setLocationRelativeTo(null);
        setTitle("InfoQuizz");
        Image Icono = mipantalla5.getImage("src/proyectofinal/imagenes/preview.jpeg");
        setIconImage(Icono);
        setResizable(false);
        back.setVisible(false); //hace invisible el boton back
        contenedorinfo.setEditable(false); // no permite que se escriba dentro del text area
        
        //Objeto jPanel con color VistaColor
        jpColor jpVista6 = new jpColor();
        jpVista6.setSize(this.getSize());       //diseño del frame
        jpVista6.setVistaColor(153,206,195,0,0,0);
        panelconsultall.add(jpVista6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelconsultall = new javax.swing.JPanel();
        muestrainfusers = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        contenedorinfo = new javax.swing.JTextArea();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        muestrainfusers.setText("Mostrar");
        muestrainfusers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                muestrainfusersMouseClicked(evt);
            }
        });

        contenedorinfo.setColumns(20);
        contenedorinfo.setRows(5);
        jScrollPane2.setViewportView(contenedorinfo);

        back.setText("Regresar");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelconsultallLayout = new javax.swing.GroupLayout(panelconsultall);
        panelconsultall.setLayout(panelconsultallLayout);
        panelconsultallLayout.setHorizontalGroup(
            panelconsultallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelconsultallLayout.createSequentialGroup()
                .addGroup(panelconsultallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelconsultallLayout.createSequentialGroup()
                        .addGap(791, 791, 791)
                        .addComponent(back)
                        .addGap(18, 18, 18)
                        .addComponent(muestrainfusers))
                    .addGroup(panelconsultallLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelconsultallLayout.setVerticalGroup(
            panelconsultallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelconsultallLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelconsultallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muestrainfusers)
                    .addComponent(back))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1017, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelconsultall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelconsultall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void muestrainfusersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muestrainfusersMouseClicked
        //boton que ayuda a mostrar todas las preguntas
        try {
            // TODO add your handling code here:
            File archlect = new File("Usuarios.dat"); //crea un objeto de tipo file con la direccion del archivo de usuarios
            RandomAccessFile entrada = new RandomAccessFile(archlect,"r"); // crea el flujo de solo lectura
            int Numuser = (int)Math.ceil((double)entrada.length()/100); //obtiene el numero de usuarios
            String usuario,contraseña; // variables que guardan los datos de cada usuario
            for (int i=0; i <= Numuser ; i++){ // ciclo para leer todas las preguntas

                entrada.seek(i*100); // se posiciona en cada inicio de pregunta
                usuario = entrada.readUTF(); // guarda usuario
                contraseña = entrada.readUTF();//guarda clave
                entrada.readFloat();

                contenedorinfo.append("Usuario "+(i+1)+"\n"); // escribe un numero de usuario leido
                contenedorinfo.append(usuario+"\n"); // imprime usuario
                contenedorinfo.append(contraseña+"\n"); // imprime contraseña
                contenedorinfo.append("\n");
                contenedorinfo.append("*****************************************"); // detalle de vista
                contenedorinfo.append("\n");
            }
        } catch (FileNotFoundException ex) {

        }catch(IOException e){

        }
        back.setVisible(true); // hace visible el boton back
        muestrainfusers.setEnabled(false); // desactiva el boton mostrar preguntas
    }//GEN-LAST:event_muestrainfusersMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:

        PantPrincipalAdmin p = new PantPrincipalAdmin(); // crea un objeto de tipo pantalla usuario
        p.setVisible(true); // hace visible el frame
        this.dispose(); // cierra el frame
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaInfoUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaInfoUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaInfoUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaInfoUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaInfoUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextArea contenedorinfo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton muestrainfusers;
    private javax.swing.JPanel panelconsultall;
    // End of variables declaration//GEN-END:variables
}
