/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class CuestionarioUser extends javax.swing.JFrame {
    private static int[]numeros;
    private static Pregunta[] asks;
    private static int i=0;
    private static int pregenArch;
    private static int correctas=0;
    private static int salida=0;
    private static int nf=0;
    private static Color v= new Color(24,229,31);
    private static Color r= new Color(242,19,31);
    private static Color b= new Color(255,255,255);
    private static boolean rc1;
    private static boolean rc2;
    private static boolean rc3;
    
    /**
     * Creates new form CuestionarioUser
     */
    public CuestionarioUser() throws IOException {
        initComponents();
        Toolkit mipantalla5 = Toolkit.getDefaultToolkit();
        setSize(1017,575);
        setLocationRelativeTo(null);
        setTitle("InfoQuizz");
        Image Icono = mipantalla5.getImage("src/proyectofinal/imagenes/preview.jpeg");
        setIconImage(Icono);
        setResizable(false);
        
        //Objeto jPanel con color VistaColor
        jpColor jpVista6 = new jpColor();
        jpVista6.setSize(this.getSize());       //diseño del frame
        jpVista6.setVistaColor(153,206,195,0,0,0);
        jPanel1.add(jpVista6);
        
         //hace los textfields no modificables
        txtTema.setEditable(false);
        txtSubt.setEditable(false);
        txtPregunta.setEditable(false);
        txtIncisoa.setEditable(false);
        txtIncisob.setEditable(false);
        txtIncisoc.setEditable(false);
        
        btnSiguiente.setVisible(false);
        btnRev.setVisible(false);
        setPregenArch();
        llenaArray();
        JOptionPane.showMessageDialog(null, "**Si marcas dos casillas la respuesta\n se considerará erronea**");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_botones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTema = new javax.swing.JTextField();
        txtSubt = new javax.swing.JTextField();
        scrollpreg = new javax.swing.JScrollPane();
        txtPregunta = new javax.swing.JTextField();
        lbladver = new javax.swing.JLabel();
        lbladver1 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnMuestraprimera = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        res1 = new javax.swing.JRadioButton();
        res2 = new javax.swing.JRadioButton();
        res3 = new javax.swing.JRadioButton();
        btnRev = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIncisoa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIncisob = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtIncisoc = new javax.swing.JTextField();
        lblCuest = new javax.swing.JLabel();
        progresocuest = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        txtTema.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTema.setText("TEMA");
        txtTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemaActionPerformed(evt);
            }
        });

        txtSubt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubt.setText("SUBTEMA");
        txtSubt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtActionPerformed(evt);
            }
        });

        txtPregunta.setText("Pregunta");
        txtPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreguntaActionPerformed(evt);
            }
        });
        scrollpreg.setViewportView(txtPregunta);

        lbladver.setText("Marque solo una casilla**");

        lbladver1.setText("Seleccione la respuesta correcta*");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });

        btnMuestraprimera.setText("Comienza");
        btnMuestraprimera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMuestraprimeraMouseClicked(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        grupo_botones.add(res1);

        grupo_botones.add(res2);

        grupo_botones.add(res3);
        res3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res3ActionPerformed(evt);
            }
        });

        btnRev.setText("Revisar");
        btnRev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRevMouseClicked(evt);
            }
        });
        btnRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevActionPerformed(evt);
            }
        });

        txtIncisoa.setText("Inciso");
        jScrollPane1.setViewportView(txtIncisoa);

        txtIncisob.setText("Inciso");
        jScrollPane2.setViewportView(txtIncisob);

        txtIncisoc.setText("Inciso");
        jScrollPane3.setViewportView(txtIncisoc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbladver, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbladver1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnMuestraprimera)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente)
                        .addGap(18, 18, 18)
                        .addComponent(btnRev))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(res2)
                            .addComponent(res3)
                            .addComponent(res1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(txtSubt, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollpreg, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSubt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollpreg, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(res2)
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(res3)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbladver1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbladver))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cancelar)
                                .addComponent(btnMuestraprimera)
                                .addComponent(btnSiguiente)
                                .addComponent(btnRev))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(res1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblCuest.setBackground(new java.awt.Color(255, 255, 255));
        lblCuest.setFont(new java.awt.Font("NSimSun", 3, 24)); // NOI18N
        lblCuest.setForeground(new java.awt.Color(255, 255, 255));
        lblCuest.setText("CUESTIONARIO");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Progreso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCuest, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(progresocuest, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel1)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCuest, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progresocuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemaActionPerformed

    private void txtSubtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtActionPerformed

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
        // TODO add your handling code here:
        btnSiguiente.setVisible(false);
        boolean alto=false;
        salida++;
        alto=cambio();
        limpiaCampos();
        i++;
        if(alto!=true)
        muestraPreg(numeros[i]);
        btnRev.setVisible(true);
        
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void btnMuestraprimeraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMuestraprimeraMouseClicked
        // TODO add your handling code here:
        btnMuestraprimera.setVisible(false);
        btnRev.setVisible(true);
        muestraPreg(numeros[i]);
    }//GEN-LAST:event_btnMuestraprimeraMouseClicked

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        // TODO add your handling code here:
        int res=0;
        res = JOptionPane.showConfirmDialog(null, "¿Seguro que quiere cancelar el cuestionario?"+"\n"+"Si sale ahora, todos su progreso se perderá");
        if(res==0){
            Menu mq = new Menu();
            mq.setVisible(true);
            this.dispose();
        }else{
            return;
        }
    }//GEN-LAST:event_cancelarMouseClicked

    private void txtPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreguntaActionPerformed

    private void res3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res3ActionPerformed

    private void btnRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevActionPerformed

    private void btnRevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevMouseClicked
        // TODO add your handling code here:
        btnRev.setVisible(false);
        double porcentaje;
        porcentaje = (100/pregenArch);
        if(comprueba(numeros[i])){
            if(progresocuest.getValue()<=100){
            progresocuest.setValue(progresocuest.getValue()+(int)(Math.ceil(porcentaje)));
            }
            correctas++;
        }
        if(rc1){txtIncisoa.setBackground(v);}else{txtIncisoa.setBackground(r);}
        if(rc2){txtIncisob.setBackground(v);}else{txtIncisob.setBackground(r);}
        if(rc3){txtIncisoc.setBackground(v);}else{txtIncisoc.setBackground(r);}
        
        btnSiguiente.setVisible(true);
    }//GEN-LAST:event_btnRevMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuestionarioUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuestionarioUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuestionarioUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuestionarioUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CuestionarioUser().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(CuestionarioUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMuestraprimera;
    private javax.swing.JButton btnRev;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton cancelar;
    private static javax.swing.ButtonGroup grupo_botones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCuest;
    private javax.swing.JLabel lbladver;
    private javax.swing.JLabel lbladver1;
    private javax.swing.JProgressBar progresocuest;
    private static javax.swing.JRadioButton res1;
    private static javax.swing.JRadioButton res2;
    private static javax.swing.JRadioButton res3;
    private javax.swing.JScrollPane scrollpreg;
    private static javax.swing.JTextField txtIncisoa;
    private static javax.swing.JTextField txtIncisob;
    private static javax.swing.JTextField txtIncisoc;
    private static javax.swing.JTextField txtPregunta;
    private static javax.swing.JTextField txtSubt;
    private static javax.swing.JTextField txtTema;
    // End of variables declaration//GEN-END:variables

    private static void limpiaCampos(){
        txtTema.setText("");
        txtSubt.setText("");
        txtPregunta.setText("");
        txtIncisoa.setText("");
        txtIncisob.setText("");
        txtIncisoc.setText("");
        res1.setSelected(false);
        res2.setSelected(false);
        res3.setSelected(false);
        grupo_botones.clearSelection();
        limpiaColor();
    }


    public static void muestraPreg(int i){
       txtTema.setText(asks[i].getTema());
       txtSubt.setText(asks[i].getSubt());
       txtPregunta.setText(asks[i].getpregunta());
       txtIncisoa.setText(asks[i].getRes1());
       txtIncisob.setText(asks[i].getRes2());
       txtIncisoc.setText(asks[i].getRes3());
    }
    
   public static boolean comprueba(int i){
        boolean rl1,rl2,rl3;
        rc1=false; rc2=false; rc3=false; rl1=false; rl2=false; rl3=false;
        rc1 = asks[i].isBres1();
        rc2 = asks[i].isBres2();
        rc3 = asks[i].isBres3();
        if(res1.isSelected()){rl1=true;}else{rl1=false;}
        if(res2.isSelected()){rl2=true;}else{rl2=false;}
        if(res3.isSelected()){rl3=true;}else{rl3=false;}
        if(rc1 == rl1){
            if(rc2 == rl2){
                if(rc3 == rl3){
                    return true;
                }
            }
            return false;
        }
        return false;

    }


    
    private static void llenaArray() throws IOException{
        RandomAccessFile flujo= new RandomAccessFile((new File("Preguntas.dat")),"r"); //abre el flujo r para escribir
        
        int i = 0,cantidad = pregenArch, rango=pregenArch;
        numeros= new int[cantidad];
        asks=new Pregunta[cantidad];
        numeros[i] = (int)(Math.random()*rango);
        for(i=1;i<cantidad;i++){
            numeros[i]=(int)(Math.random()*rango);
            for(int j=0;j<i;j++){
                if(numeros[i]==numeros[j])
                    i--;
            }
        }
  
        for(int a=0;a<cantidad;a++){                //recorre el arreglo de numeros aleatorios
            String Tema,Subtema,Pregunta,inc1,inc2,inc3;
            boolean ra1,ra2,ra3;
            flujo.seek((numeros[a])*1200);                 // se usa para posicionar un punto en el archivo
            Tema=flujo.readUTF();
            Subtema=flujo.readUTF();
            Pregunta=flujo.readUTF();
            inc1=flujo.readUTF();
            ra1=flujo.readBoolean();
            inc2=flujo.readUTF();
            ra2=flujo.readBoolean();
            inc3=flujo.readUTF();
            ra3=flujo.readBoolean();
            asks[a]= new Pregunta(Tema,Subtema,Pregunta,inc1,ra1,inc2,ra2,inc3,ra3); //guarda onjetos de tipo pregunta
        }
        flujo.close();
        System.out.println(asks.length);
    }
    
    private static void setPregenArch() throws IOException{
        File preguntas = new File("Preguntas.dat");
        RandomAccessFile flujopreguntas = new RandomAccessFile(preguntas,"r");
        pregenArch = (int)Math.ceil((flujopreguntas.length()/(double)1200)); //me dice el numero de preguntas en el archivo
        flujopreguntas.close();
    }
    
    private boolean cambio(){
        if (salida>=pregenArch){
            if(nf<1){
                try {
                    Thread.sleep(3000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(CuestionarioUser.class.getName()).log(Level.SEVERE, null, ex);
                }
                Resultados res=new Resultados();
                res.setVisible(true);
                this.dispose();
                nf++;
            }
            
            return true;
        }
        return false;
    }
    public static float getCorrectas(){
        return (float)correctas;
    }
    public static float getPregenArch(){
        return (float)pregenArch;
    }
    
    public static void setInicializadores(int a, int b, int c, int d){
        correctas = a;
        salida = b;
        nf = c;
        i = d;
    }
    
    private static void limpiaColor(){
        txtIncisoa.setBackground(b);
        txtIncisob.setBackground(b);
        txtIncisoc.setBackground(b);
    }
 
}
