/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Modifpreg extends javax.swing.JFrame {
    
    CamposPModif cpm = new CamposPModif();

    /**
     * Creates new form Modifpreg
     */
    public Modifpreg() {
        initComponents();
        Toolkit mipantalla4 = Toolkit.getDefaultToolkit();
        setSize(1017,575);
        setLocationRelativeTo(null);
        setTitle("InfoQuizz");
        Image Icono = mipantalla4.getImage("src/proyectofinal/imagenes/preview.jpeg");
        setIconImage(Icono);
        setResizable(false);
        
        //Objeto jPanel con color VistaColor
        jpColor jpVista6 = new jpColor();
        jpVista6.setSize(this.getSize());
        jpVista6.setVistaColor(153,206,195,0,0,0);
        contenedor.add(jpVista6);
        
        campospreg.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        panelbotones = new javax.swing.JPanel();
        cancelar = new javax.swing.JButton();
        npreg = new javax.swing.JButton();
        campospreg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedor.setLayout(new java.awt.BorderLayout());

        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });
        panelbotones.add(cancelar);

        npreg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        npreg.setText("Ingrese número de pregunta");
        npreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                npregMouseClicked(evt);
            }
        });
        panelbotones.add(npreg);

        campospreg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        campospreg.setText("Llenar campos de la nueva pregunta");
        campospreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campospregMouseClicked(evt);
            }
        });
        panelbotones.add(campospreg);

        contenedor.add(panelbotones, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        // TODO add your handling code here:
        PantPrincipalAdmin regresomodif = new PantPrincipalAdmin();
        regresomodif.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarMouseClicked

    private void npregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_npregMouseClicked
        // TODO add your handling code here:
        CamposPModif.setPosicion(Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de pregunta\n(puede consultarlo en el campo 'Mostrar todo')")));
        campospreg.setEnabled(true);
    }//GEN-LAST:event_npregMouseClicked

    private void campospregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campospregMouseClicked
        // TODO add your handling code here:
        contenedor.add(cpm);
    }//GEN-LAST:event_campospregMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifpreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifpreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifpreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifpreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifpreg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton campospreg;
    private javax.swing.JButton cancelar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton npreg;
    private javax.swing.JPanel panelbotones;
    // End of variables declaration//GEN-END:variables
}
