package proyectofinal;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Resultados extends javax.swing.JFrame {
    
    private static float Puntaje;
    private static float Acertadas=0;
    private static float Reactivos=0;
    private static int posicionuser;

    /**
     * Creates new form Resultados
     */
    public Resultados() {
        initComponents();
        Toolkit mipantalla4 = Toolkit.getDefaultToolkit(); //obtiene informacion de la pantalla y lo guarda en el objeto
        setSize(1017,575); // establece el tamaño de la pantalla 
        setLocationRelativeTo(null); // establece la posicion de la pantalla en el centro
        setTitle("InfoQuizz"); //Establece el titulo
        Image Icono = mipantalla4.getImage("src/proyectofinal/imagenes/preview.jpeg"); //Se crea un objeto de tipo Image
        setIconImage(Icono); // Se usa el objeto image para colocar icono
        setResizable(false); //esto impode que agranden la pantalla
        
        //Objeto jPanel con color VistaColor
        jpColor jpVista5 = new jpColor();
        jpVista5.setSize(this.getSize());  //esta funcion hace el color degradado en el panel
        jpVista5.setVistaColor(153,206,195,0,0,0);
        jPanel1.add(jpVista5);
        
        //hace los textfields no editables
        txtAcertadas.setEditable(false);
        txtErroneas.setEditable(false);
        txtPuntaje.setEditable(false);
        txtRetro.setEditable(false);
        
        btnSalir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFelicitaciones = new javax.swing.JLabel();
        lblResultados = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAcertadas = new javax.swing.JTextField();
        txtPuntaje = new javax.swing.JTextField();
        txtErroneas = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnMuestra = new javax.swing.JButton();
        lblretro = new javax.swing.JLabel();
        txtRetro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFelicitaciones.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        lblFelicitaciones.setForeground(new java.awt.Color(255, 255, 255));
        lblFelicitaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFelicitaciones.setText("¡¡Felicitaciones, has concluido el cuestionario!!");

        lblResultados.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblResultados.setForeground(new java.awt.Color(255, 255, 255));
        lblResultados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultados.setText("RESULTADOS");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 170, 160));
        jLabel1.setText("Acertadas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 170, 160));
        jLabel2.setText("Erroneas");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(199, 218, 40));
        jLabel3.setText("Puntaje ");

        txtAcertadas.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        txtAcertadas.setForeground(new java.awt.Color(32, 170, 160));

        txtPuntaje.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        txtPuntaje.setForeground(new java.awt.Color(199, 218, 40));

        txtErroneas.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        txtErroneas.setForeground(new java.awt.Color(32, 170, 160));

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        btnMuestra.setText("Muestra puntaje");
        btnMuestra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMuestraMouseClicked(evt);
            }
        });
        btnMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuestraActionPerformed(evt);
            }
        });

        lblretro.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblretro.setForeground(new java.awt.Color(255, 255, 255));
        lblretro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblretro.setText("Retroalimentacion");

        txtRetro.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        txtRetro.setForeground(new java.awt.Color(82, 23, 160));
        txtRetro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAcertadas)
                            .addComponent(txtPuntaje, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtErroneas, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblretro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRetro, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMuestra)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir))
                    .addComponent(lblFelicitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFelicitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAcertadas)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtErroneas, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblretro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRetro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPuntaje)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnMuestra))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuestraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMuestraActionPerformed

    private void btnMuestraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMuestraMouseClicked
        // TODO add your handling code here:
        btnSalir.setVisible(true);
        setEntradas();
        ObtenPuntaje();
        MuestraResultados();
        MuestraPuntaje();
        if(escribepuntaje())
            JOptionPane.showMessageDialog(null, "¡Puntaje guardado exitosamente!;)");
        btnMuestra.setVisible(false);
    }//GEN-LAST:event_btnMuestraMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        Menu ms = new Menu();
        ms.setVisible(true);
        JOptionPane.showMessageDialog(null, "Para realizar nuevamente el cuestionario, ingrese con otro usuario");
        dispose();
        CuestionarioUser.setInicializadores(0,0,0,0);
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMuestra;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFelicitaciones;
    private javax.swing.JLabel lblResultados;
    private javax.swing.JLabel lblretro;
    private static javax.swing.JTextField txtAcertadas;
    private static javax.swing.JTextField txtErroneas;
    private static javax.swing.JTextField txtPuntaje;
    private static javax.swing.JTextField txtRetro;
    // End of variables declaration//GEN-END:variables

    private static float getPuntaje(){
        return Puntaje;
    }
    
    private static void ObtenPuntaje(){
        float ptjebase;
        float ptjefinal;
        float decimales;
        
        ptjebase = ((Acertadas/Reactivos)*100);
        decimales = ptjebase;
        ptjebase = (float)Math.floor(ptjebase);
        
        decimales = ((decimales-ptjebase)*100);
        decimales = (float)Math.round(decimales);
        ptjefinal = (ptjebase+(decimales/100));
        
        Puntaje=ptjefinal;
    }
    
    private static void MuestraResultados(){
        String Acertadas,Erroneas;
        float acertadas=0,erroneas=0;
        acertadas=CuestionarioUser.getCorrectas();
        erroneas=(CuestionarioUser.getPregenArch()-acertadas);
        
        Acertadas = ""+(int)acertadas;
        Erroneas = ""+(int)erroneas;
        
        txtAcertadas.setText(Acertadas);
        txtErroneas.setText(Erroneas);
        
    }
    
    private static void MuestraPuntaje(){
        String puntajestring;
        puntajestring=""+getPuntaje()+" de 100";
        txtPuntaje.setText(puntajestring);
        retroalimentacion();
    }
    
    private static void setEntradas(){
        Acertadas = CuestionarioUser.getCorrectas();
        Reactivos = CuestionarioUser.getPregenArch();
    }
    
    private static void retroalimentacion(){
        if(getPuntaje()>=0.00f && getPuntaje()<=59.99f){
            txtRetro.setText("Necesitas mejorar :(");
        }
        if(getPuntaje()>=60.00f && getPuntaje()<=69.99f){
            txtRetro.setText("Puntaje mínimo :/");
        }
        if(getPuntaje()>=70.00f && getPuntaje()<=80.99f){
            txtRetro.setText("Puntaje regular :)");
        }
        if(getPuntaje()>=90.00f &&getPuntaje()<=100.00f){
            txtRetro.setText("Puntaje Excelente!!! ;)");
        }
    }
    
    private static boolean escribepuntaje(){
        try {
            File users = new File("Usuarios.dat");
            RandomAccessFile escribe = new RandomAccessFile(users,"rw");
            posicionuser = Menu.getNumerouser();
            
            escribe.seek(posicionuser*100);
            escribe.readUTF();
            escribe.readUTF();
            escribe.writeFloat(getPuntaje());
            escribe.close();
            return true;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Resultados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Resultados.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
}
